let song_data = [
    {
        "_id": "61460e91efd0d795bff2e3d5",
        "title": "Gallo Ciego",
        "desc": "",
        "favourite": true,
        "filename": "01-GalloCiego.mp3",
        "src": "music/01-GalloCiego.mp3",
        "artist": "Osváldo Pugliese",
        "quality": 3,
        "play_count": 0,
        "genre": "Tango",
        "album": "Instrumentales Inolvidables Vol 3",
        "size": 3450880,
        "duration": 215.589
    },
    {
        "_id": "61460ec8efd0d795bff2e3d6",
        "title": "Yunta De Oro",
        "desc": "",
        "favourite": true,
        "filename": "02-YuntaDeOro.mp3",
        "src": "music/02-YuntaDeOro.mp3",
        "artist": "Osváldo Pugliese",
        "quality": 5,
        "play_count": 0,
        "genre": "Tango",
        "album": "Instrumentales Inolvidables Vol 3",
        "size": 3416064,
        "duration": 213.42
    },
    {
        "_id": "61460edcefd0d795bff2e3d7",
        "title": "Quejumbroso",
        "desc": "",
        "favourite": false,
        "filename": "03-Quejumbroso.mp3",
        "src": "music/03-Quejumbroso.mp3",
        "artist": "Osváldo Pugliese",
        "quality": 5,
        "play_count": 0,
        "genre": "Tango",
        "album": "Instrumentales Inolvidables Vol 3",
        "size": 3459072,
        "duration": 216.007
    },
    {
        "_id": "61460f34fd594a37613d7aa6",
        "title": "Mato Y Voy",
        "desc": "",
        "favourite": false,
        "filename": "04-MatoYVoy.mp3",
        "src": "music/04-MatoYVoy.mp3",
        "artist": "Osváldo Pugliese",
        "quality": 5,
        "play_count": 0,
        "genre": "Tango",
        "album": "Instrumentales Inolvidables Vol 3",
        "size": 3434496,
        "duration": 214.596
    },
    {
        "_id": "61460f3efd594a37613d7aa7",
        "title": "Pata Ancha",
        "desc": "",
        "favourite": true,
        "filename": "05-PataAncha.mp3",
        "src": "music/05-PataAncha.mp3",
        "artist": "Osváldo Pugliese",
        "quality": 5,
        "play_count": 0,
        "genre": "Tango",
        "album": "Instrumentales Inolvidables Vol 3",
        "size": 3258368,
        "duration": 203.468
    },
    {
        "_id": "614610babcfe881c3287c1d0",
        "title": "Symphony No.1 in C-dur, Op.21 - I. Adagio molto - Allegro con brio",
        "desc": "",
        "favourite": false,
        "filename": "01SymphonyNo1inC-durOp21-IAdagiomolto-Allegroconbrio.mp3",
        "src": "music/01SymphonyNo1inC-durOp21-IAdagiomolto-Allegroconbrio.mp3",
        "artist": "Beethoven (Klemperer)",
        "quality": 5,
        "play_count": 0,
        "genre": "Classical",
        "album": "Complete Symphonies and Piano Concertos",
        "size": 23808043,
        "duration": 595.096
    },
    {
        "_id": "614610dabcfe881c3287c1d1",
        "title": "Symphony No.3 in Es-dur, Op.55 - I. Allegro con brio",
        "desc": "",
        "favourite": false,
        "filename": "01SymphonyNo3inEs-durOp55-IAllegroconbrio.mp3",
        "src": "music/01SymphonyNo3inEs-durOp55-IAllegroconbrio.mp3",
        "artist": "Beethoven (Klemperer)",
        "quality": 5,
        "play_count": 0,
        "genre": "Classical",
        "album": "Complete Symphonies and Piano Concertos",
        "size": 40053072
    },
    {
        "_id": "614610f3bcfe881c3287c1d2",
        "title": "Symphony No.2 in D-dur, Op.36 - I. Adagio molto - Allegro con brio",
        "desc": "",
        "favourite": true,
        "filename": "01SymphonyNo2inD-durOp36-IAdagiomolto-Allegroconbrio.mp3",
        "src": "music/01SymphonyNo2inD-durOp36-IAdagiomolto-Allegroconbrio.mp3",
        "artist": "Beethoven (Klemperer)",
        "quality": 5,
        "play_count": 0,
        "genre": "Classical",
        "album": "Complete Symphonies and Piano Concertos",
        "size": 32296794,
        "duration": 807.314
    },
    {
        "_id": "6146110ebcfe881c3287c1d3",
        "title": "Symphony No.4 in B-dur, Op.60 - I. Adagio - Allegro vivace",
        "desc": "",
        "favourite": false,
        "filename": "01SymphonyNo4inB-durOp60-IAdagio-Allegrovivace.mp3",
        "src": "music/01SymphonyNo4inB-durOp60-IAdagio-Allegrovivace.mp3",
        "artist": "Beethoven (Klemperer)",
        "quality": 6,
        "play_count": 0,
        "genre": "Classical",
        "album": "Complete Symphonies and Piano Concertos",
        "size": 29912337,
        "duration": 747.703
    },
    {
        "_id": "6146111fbcfe881c3287c1d4",
        "title": "Symphony No.7 in A-dur, Op.92 - I. Poco sostenuto - Vivace",
        "desc": "",
        "favourite": false,
        "filename": "05SymphonyNo7inA-durOp92-IPocosostenuto-Vivace.mp3",
        "src": "music/05SymphonyNo7inA-durOp92-IPocosostenuto-Vivace.mp3",
        "artist": "Beethoven (Klemperer)",
        "quality": 5,
        "play_count": 0,
        "genre": "Classical",
        "album": "Complete Symphonies and Piano Concertos",
        "size": 30887227,
        "duration": 772.075
    },
    {
        "_id": "6146115fbcfe881c3287c1d5",
        "title": "Je chante",
        "desc": "",
        "favourite": false,
        "filename": "01-Jechante.mp3",
        "src": "music/01-Jechante.mp3",
        "artist": "Charles Trenet",
        "quality": 1,
        "play_count": 0,
        "genre": "Pop",
        "album": "CD 01: 1937-1939",
        "size": 6754967,
        "duration": 167.445
    },
    {
        "_id": "61461192bcfe881c3287c1d6",
        "title": "Vous oubliez votre cheval",
        "desc": "",
        "favourite": false,
        "filename": "10-Vousoubliezvotrecheval.mp3",
        "src": "music/10-Vousoubliezvotrecheval.mp3",
        "artist": "Charles Trenet",
        "quality": 10,
        "play_count": 0,
        "genre": "Pop",
        "album": "CD 01: 1937-1939",
        "size": 7272224,
        "duration": 180.376
    },
    {
        "_id": "614611b1bcfe881c3287c1d7",
        "title": "Boum!",
        "desc": "",
        "favourite": false,
        "filename": "13-Boum.mp3",
        "src": "music/13-Boum.mp3",
        "artist": "Charles Trenet",
        "quality": 5,
        "play_count": 0,
        "genre": "Pop",
        "album": "CD 01: 1937-1939",
        "size": 6227286,
        "duration": 154.253
    },
    {
        "_id": "614611e6bcfe881c3287c1d8",
        "title": "Symphony in F, K.App.223",
        "desc": "",
        "favourite": false,
        "filename": "SymphonyinFKApp223.mp3",
        "src": "music/SymphonyinFKApp223.mp3",
        "artist": "Wiener Philharmoniker, James Levine",
        "quality": 8,
        "play_count": 0,
        "genre": "Classical",
        "album": "Mozart: The Symphonies",
        "size": 18413848,
        "duration": 777.038
    },
    {
        "_id": "614612c5d2d41eda85d44124",
        "title": "Symphony No.1 in E-Flat, K.16",
        "desc": "",
        "favourite": false,
        "filename": "SymphonyNo1inE-FlatK16.mp3",
        "src": "music/SymphonyNo1inE-FlatK16.mp3",
        "artist": "Wiener Philharmoniker, James Levine",
        "quality": 6,
        "play_count": 0,
        "genre": "Classical",
        "album": "Mozart: The Symphonies",
        "size": 20259085,
        "duration": 858.697
    },
    {
        "_id": "614612eed2d41eda85d44125",
        "title": "Symphony No.4 in D, K.19",
        "desc": "",
        "favourite": true,
        "filename": "SymphonyNo4inDK19.mp3",
        "src": "music/SymphonyNo4inDK19.mp3",
        "artist": "Wiener Philharmoniker, James Levine",
        "quality": 2,
        "play_count": 0,
        "genre": "Classical",
        "album": "Mozart: The Symphonies",
        "size": 16772338,
        "duration": 700.473
    },
    {
        "_id": "6146137ad2d41eda85d44126",
        "title": "Bright Size Life",
        "desc": "",
        "favourite": false,
        "filename": "01BrightSizeLife.mp3",
        "src": "music/01BrightSizeLife.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "size": 11471716,
        "duration": 285.205
    },
    {
        "_id": "61461382d2d41eda85d44127",
        "title": "Sirabhorn",
        "desc": "",
        "favourite": false,
        "filename": "02Sirabhorn.mp3",
        "src": "music/02Sirabhorn.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "size": 13252208,
        "duration": 329.718
    },
    {
        "_id": "61461388d2d41eda85d44128",
        "title": "Unity Village",
        "desc": "",
        "favourite": false,
        "filename": "03UnityVillage.mp3",
        "src": "music/03UnityVillage.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "size": 8875138,
        "duration": 220.291
    },
    {
        "_id": "614616e848dcefcf9ec22f83",
        "title": "Missouri Uncompromised",
        "desc": "",
        "favourite": true,
        "filename": "04MissouriUncompromised.mp3",
        "src": "music/04MissouriUncompromised.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "size": 10537589,
        "duration": 261.851
    },
    {
        "_id": "61461d3c92d31e6041bf5503",
        "title": "Midwestern Nights Dream",
        "desc": "",
        "favourite": true,
        "filename": "05MidwesternNightsDream.mp3",
        "src": "music/05MidwesternNightsDream.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "duration": 360.673,
        "size": 14490440
    },
    {
        "_id": "61461efd5d9b880240dda9c0",
        "title": "Unquity Road",
        "desc": "",
        "favourite": false,
        "filename": "06UnquityRoad.mp3",
        "src": "music/06UnquityRoad.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "duration": 215.562,
        "missing_file": true
    },
    {
        "_id": "61463308e71ee3d8bdd0b7bc",
        "title": "Omaha Celebration",
        "desc": "",
        "favourite": false,
        "filename": "07OmahaCelebration.mp3",
        "src": "music/07OmahaCelebration.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "duration": 258.717,
        "size": 10412191
    },
    {
        "_id": "6146340dc081201e0fcb5222",
        "title": "Round Trip, Broadway Blues",
        "desc": "",
        "favourite": false,
        "filename": "08RoundTripBroadwayBlues.mp3",
        "src": "music/08RoundTripBroadwayBlues.mp3",
        "artist": "Pat Metheny",
        "quality": 5,
        "play_count": 0,
        "genre": "Jazz",
        "album": "Bright Size Life",
        "duration": 298.214,
        "size": 11992095
    },
    {
        "_id": "615c225fcf19dbdb3c968a60",
        "title": "One",
        "desc": "",
        "favourite": false,
        "filename": "one.mp3",
        "src": "music/one.mp3",
        "artist": "Tessa",
        "quality": 5,
        "play_count": 0,
        "genre": "Vocal",
        "album": "Numbers",
        "duration": 0.731,
        "size": 4355
    },
    {
        "_id": "615c227dcf19dbdb3c968a61",
        "title": "Two",
        "desc": "",
        "favourite": false,
        "filename": "two.mp3",
        "src": "music/two.mp3",
        "artist": "Samantha",
        "quality": 5,
        "play_count": 0,
        "genre": "Vocal",
        "album": "Numbers",
        "duration": 0.731,
        "size": 4358
    },
    {
        "_id": "615c2286cf19dbdb3c968a62",
        "title": "Three",
        "desc": "",
        "favourite": false,
        "filename": "three.mp3",
        "src": "music/three.mp3",
        "artist": "Moira",
        "quality": 5,
        "play_count": 0,
        "genre": "Vocal",
        "album": "Numbers",
        "duration": 0.784,
        "size": 4566
    },
    {
        "_id": "615c228ecf19dbdb3c968a63",
        "title": "Four",
        "desc": "",
        "favourite": false,
        "filename": "four.mp3",
        "src": "music/four.mp3",
        "artist": "Alex",
        "quality": 5,
        "play_count": 0,
        "genre": "Vocal",
        "album": "Numbers",
        "duration": 11.781,
        "size": 48538
    },
    {
        "_id": "615c22b5cf19dbdb3c968a65",
        "title": "Counting to twelve",
        "desc": "",
        "favourite": false,
        "filename": "five.mp3",
        "src": "music/five.mp3",
        "artist": "Pentatonix",
        "quality": 5,
        "play_count": 0,
        "genre": "Pop",
        "album": "Numbers",
        "duration": 10.057,
        "size": 161934
    },
    {
        "_id": "615c22bbcf19dbdb3c968a66",
        "title": "Six",
        "desc": "",
        "favourite": false,
        "filename": "six.mp3",
        "src": "music/six.mp3",
        "artist": "Renée Fleming",
        "quality": 5,
        "play_count": 0,
        "genre": "Opera",
        "album": "Numbers",
        "duration": 25.182,
        "size": 1007500
    },
    {
        "_id": "615c22c1cf19dbdb3c968a67",
        "title": "Seven",
        "desc": "",
        "favourite": false,
        "filename": "seven.mp3",
        "src": "music/seven.mp3",
        "artist": "Marion Cotillard",
        "quality": 5,
        "play_count": 0,
        "genre": "Vocal",
        "album": "Numbers",
        "duration": 12.048,
        "size": 193795
    }
]